version: "3.8"

services:
  bitcoin-core-regtest:
    build:
      context: .
      args:
        TARGETPLATFORM: "linux/amd64"
    volumes:
      - ./btc/:/home/bitcoin/.bitcoin
    environment:
      - UID=$UID
      - GID=$GID
    ports:
      - "8332:8332"
    #
    #Dont know which flags are actually required, but it works now so not changing it.
    command:
      -printtoconsole
      -regtest=1
      -rpcport=8332
      -rpcuser=dennis
      -rpcpassword=test
      -rpcallowip=127.0.0.1
      -rpcallowip=192.168.0.152
      -server=1
      -daemon=0
      -rpcbind=127.0.0.1
      -rpcbind=172.19.0.2
      -fallbackfee=0.0001